[qnode0023:955841] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[qnode0022:3816763] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[qnode0024:3248046] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[qnode0021:3642948] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
Traceback (most recent call last):
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 379, in <module>
    main()
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 375, in main
    print(f"RESULT: job_id={os.environ.get('SLURM_JOB_ID')} total_time={total_time.total_seconds()} partition_time={partition_time.total_seconds()} local_join_time={join_time.total_seconds()} collection_time={collection_time.total_seconds()}")
NameError: name 'join_time' is not defined
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[43482,1],0]
  Exit code:    1
--------------------------------------------------------------------------
